//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsms.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKS_Provider
    {
        public CKS_Provider()
        {
            this.CKS_AgentProvider = new HashSet<CKS_AgentProvider>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<CKS_AgentProvider> CKS_AgentProvider { get; set; }
    }
}
