//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsms.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKS_AgentUser
    {
        public int Id { get; set; }
        public int AgentId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual CKS_Agent CKS_Agent { get; set; }
    }
}
