//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsms.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKS_TokenType
    {
        public CKS_TokenType()
        {
            this.CKS_AgentTokenType = new HashSet<CKS_AgentTokenType>();
        }
    
        public int Id { get; set; }
        public int ProviderId { get; set; }
        public string Title { get; set; }
        public int Duration { get; set; }
    
        public virtual ICollection<CKS_AgentTokenType> CKS_AgentTokenType { get; set; }
    }
}
