//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsms.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKS_Contract
    {
        public int Id { get; set; }
        public int TokenType { get; set; }
        public int CompanyId { get; set; }
        public int AgentId { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Price { get; set; }
        public int Amount { get; set; }
        public int DiscountPercent { get; set; }
        public int Discount { get; set; }
        public int ContractType { get; set; }
        public int ContractDuration { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CKS_Agent CKS_Agent { get; set; }
        public virtual CKS_Company CKS_Company { get; set; }
    }
}
